name: JAR-builder
run-name: Your application is building...
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: workflow_secrets
    steps:
      - uses: actions/checkout@v3 #clones repo on to runner VM
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven wrapper
        run: ./mvnw package

      - name: Copies a built artifact to destination folder
        run: mkdir artifacts && cp target/*.jar artifacts/your_artifact.jar
      - name: Uploads a built artifact to destination folder  
        uses: actions/upload-artifact@v3
        with:
          name: built_artifact
          path: artifacts
        # test
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
           
          port: 22
          #key: ${{ secrets.SSH_KEY }}
          #passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        #  rm: true
          password: ${{ secrets.PASSWORD }}
          source: "artifacts"
          target: "${{ secrets.REMOTE_DIR }}"